master:
  steps:
    - image: maven:3.6.0-jdk-8-alpine
      commands:
        - mvn install
branch:
  steps:
    - image: maven:3.6.0-jdk-8-alpine
      commands:
        - mvn clean
    - image: maven:3.6.0-jdk-8-alpine
      commands:
        - mvn install
        - mvn sonar:sonar


